import type {
  Product,
  SellerProfile,
  BuyerProfile,
  Order,
  Review,
  Notification,
  Conversation,
  Message,
  Address,
  Cart,
  SellerAnalytics,
} from '@/types';

// Mock Sellers
export const mockSellers: SellerProfile[] = [
  {
    id: 'seller-1',
    email: 'chikwanha@agromarket.zw',
    phone: '+263 77 123 4567',
    firstName: 'Tendai',
    lastName: 'Chikwanha',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    isVerified: true,
    businessName: 'Chikwanha Farms',
    businessDescription: 'Premium pork and farm produce from the heart of Mashonaland. Family-owned since 1985.',
    location: 'Harare, Zimbabwe',
    rating: 4.8,
    totalReviews: 324,
    totalSales: 1250,
    badges: ['verified', 'top_seller', 'trusted_farm'],
    kycStatus: 'verified',
    isActive: true,
    createdAt: '2022-03-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'seller-2',
    email: 'moyo@agromarket.zw',
    phone: '+263 71 987 6543',
    firstName: 'Grace',
    lastName: 'Moyo',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    isVerified: true,
    businessName: 'Moyo Fresh Vegetables',
    businessDescription: 'Fresh organic vegetables grown with care. Direct from farm to your table.',
    location: 'Bulawayo, Zimbabwe',
    rating: 4.6,
    totalReviews: 189,
    totalSales: 890,
    badges: ['verified', 'fast_delivery'],
    kycStatus: 'verified',
    isActive: true,
    createdAt: '2022-06-20T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'seller-3',
    email: 'ncube@agromarket.zw',
    phone: '+263 73 456 7890',
    firstName: 'Blessing',
    lastName: 'Ncube',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    isVerified: true,
    businessName: 'Ncube Grain Traders',
    businessDescription: 'Quality grains and cereals. Bulk orders welcome.',
    location: 'Mutare, Zimbabwe',
    rating: 4.5,
    totalReviews: 156,
    totalSales: 720,
    badges: ['verified', 'premium'],
    kycStatus: 'verified',
    isActive: true,
    createdAt: '2022-09-10T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
];

// Mock Products
export const mockProducts: Product[] = [
  // Pork Meat Products
  {
    id: 'prod-1',
    sellerId: 'seller-1',
    sellerName: 'Chikwanha Farms',
    sellerRating: 4.8,
    sellerBadges: ['verified', 'top_seller', 'trusted_farm'],
    name: 'Premium Pork Loin',
    slug: 'premium-pork-loin',
    category: 'pork_meat',
    subcategory: 'Loin',
    description: 'Premium quality pork loin from free-range pigs. Perfect for roasting, grilling, or slicing into chops. Our pigs are raised on natural feed without hormones or antibiotics.',
    shortDescription: 'Fresh free-range pork loin, perfect for roasting',
    price: 12.99,
    discountedPrice: 10.99,
    currency: 'USD',
    stockQuantity: 50,
    unit: 'kg',
    weight: 1,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Harare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-1', url: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=600&h=400&fit=crop', alt: 'Premium Pork Loin', isPrimary: true },
      { id: 'img-2', url: 'https://images.unsplash.com/photo-1588347785102-4b45817fbc09?w=600&h=400&fit=crop', alt: 'Pork Loin Sliced', isPrimary: false },
    ],
    tags: ['premium', 'free-range', 'fresh', 'roasting'],
    sku: 'PORK-LOIN-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.9,
    totalReviews: 87,
    isFeatured: true,
    isOnSale: true,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-2',
    sellerId: 'seller-1',
    sellerName: 'Chikwanha Farms',
    sellerRating: 4.8,
    sellerBadges: ['verified', 'top_seller', 'trusted_farm'],
    name: 'Pork Ribs - Baby Back',
    slug: 'pork-ribs-baby-back',
    category: 'pork_meat',
    subcategory: 'Ribs',
    description: 'Tender baby back ribs, perfect for BBQ. Meaty and flavorful, these ribs are a crowd favorite.',
    shortDescription: 'Tender baby back ribs for BBQ',
    price: 15.99,
    currency: 'USD',
    stockQuantity: 35,
    unit: 'kg',
    weight: 1.5,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Harare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-3', url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop', alt: 'Baby Back Ribs', isPrimary: true },
    ],
    tags: ['bbq', 'ribs', 'tender', 'grilling'],
    sku: 'PORK-RIBS-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.7,
    totalReviews: 62,
    isFeatured: true,
    isOnSale: false,
    createdAt: '2024-01-02T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
  },
  {
    id: 'prod-3',
    sellerId: 'seller-1',
    sellerName: 'Chikwanha Farms',
    sellerRating: 4.8,
    sellerBadges: ['verified', 'top_seller', 'trusted_farm'],
    name: 'Ground Pork Mince',
    slug: 'ground-pork-mince',
    category: 'pork_meat',
    subcategory: 'Mince',
    description: 'Freshly ground pork mince. Ideal for meatballs, burgers, dumplings, and stir-fries.',
    shortDescription: 'Fresh ground pork for versatile cooking',
    price: 8.99,
    currency: 'USD',
    stockQuantity: 100,
    unit: 'kg',
    weight: 0.5,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Harare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-4', url: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&h=400&fit=crop', alt: 'Ground Pork', isPrimary: true },
    ],
    tags: ['mince', 'versatile', 'cooking'],
    sku: 'PORK-MINCE-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.6,
    totalReviews: 45,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-03T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
  {
    id: 'prod-4',
    sellerId: 'seller-1',
    sellerName: 'Chikwanha Farms',
    sellerRating: 4.8,
    sellerBadges: ['verified', 'top_seller', 'trusted_farm'],
    name: 'Pork Belly Slab',
    slug: 'pork-belly-slab',
    category: 'pork_meat',
    subcategory: 'Belly',
    description: 'Rich and flavorful pork belly slab. Perfect for slow roasting, braising, or making bacon.',
    shortDescription: 'Rich pork belly for slow cooking',
    price: 11.49,
    discountedPrice: 9.99,
    currency: 'USD',
    stockQuantity: 25,
    unit: 'kg',
    weight: 2,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Harare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-5', url: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=600&h=400&fit=crop', alt: 'Pork Belly', isPrimary: true },
    ],
    tags: ['belly', 'slow-cook', 'roasting'],
    sku: 'PORK-BELLY-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.8,
    totalReviews: 53,
    isFeatured: true,
    isOnSale: true,
    createdAt: '2024-01-04T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: 'prod-5',
    sellerId: 'seller-1',
    sellerName: 'Chikwanha Farms',
    sellerRating: 4.8,
    sellerBadges: ['verified', 'top_seller', 'trusted_farm'],
    name: 'Smoked Bacon Rashers',
    slug: 'smoked-bacon-rashers',
    category: 'pork_meat',
    subcategory: 'Bacon',
    description: 'Traditional smoked bacon rashers. Crispy and delicious for breakfast or sandwiches.',
    shortDescription: 'Crispy smoked bacon rashers',
    price: 14.99,
    currency: 'USD',
    stockQuantity: 80,
    unit: 'pack',
    weight: 0.5,
    weightUnit: 'kg',
    freshnessType: 'processed',
    location: 'Harare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery', 'nationwide'],
    images: [
      { id: 'img-6', url: 'https://images.unsplash.com/photo-1606851181064-3939e5e5b3e1?w=600&h=400&fit=crop', alt: 'Smoked Bacon', isPrimary: true },
    ],
    tags: ['bacon', 'smoked', 'breakfast'],
    sku: 'PORK-BACON-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.9,
    totalReviews: 120,
    isFeatured: true,
    isOnSale: false,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-01-11T10:00:00Z',
  },
  // Fresh Crops & Vegetables
  {
    id: 'prod-6',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Organic Tomatoes',
    slug: 'organic-tomatoes',
    category: 'vegetables',
    subcategory: 'Tomatoes',
    description: 'Fresh organic tomatoes grown without pesticides. Sweet and juicy, perfect for salads or cooking.',
    shortDescription: 'Fresh organic tomatoes, sweet and juicy',
    price: 3.49,
    currency: 'USD',
    stockQuantity: 200,
    unit: 'kg',
    weight: 1,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-7', url: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=600&h=400&fit=crop', alt: 'Organic Tomatoes', isPrimary: true },
    ],
    tags: ['organic', 'fresh', 'salad', 'cooking'],
    sku: 'VEG-TOM-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 2,
    averageRating: 4.5,
    totalReviews: 78,
    isFeatured: true,
    isOnSale: false,
    createdAt: '2024-01-06T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'prod-7',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Fresh Spinach Bunch',
    slug: 'fresh-spinach-bunch',
    category: 'vegetables',
    subcategory: 'Leafy Greens',
    description: 'Nutrient-rich fresh spinach. Packed with vitamins and minerals for healthy eating.',
    shortDescription: 'Fresh nutrient-rich spinach',
    price: 1.99,
    currency: 'USD',
    stockQuantity: 150,
    unit: 'bunch',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-8', url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&h=400&fit=crop', alt: 'Fresh Spinach', isPrimary: true },
    ],
    tags: ['leafy', 'healthy', 'vitamins'],
    sku: 'VEG-SPIN-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.4,
    totalReviews: 34,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-07T10:00:00Z',
    updatedAt: '2024-01-09T10:00:00Z',
  },
  {
    id: 'prod-8',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Fresh Onions',
    slug: 'fresh-onions',
    category: 'vegetables',
    subcategory: 'Onions',
    description: 'Fresh locally grown onions. Essential for every kitchen.',
    shortDescription: 'Fresh local onions',
    price: 2.49,
    currency: 'USD',
    stockQuantity: 300,
    unit: 'kg',
    weight: 1,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-9', url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=600&h=400&fit=crop', alt: 'Fresh Onions', isPrimary: true },
    ],
    tags: ['cooking', 'essential', 'local'],
    sku: 'VEG-ONION-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 2,
    averageRating: 4.6,
    totalReviews: 56,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: 'prod-9',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Sweet Potatoes',
    slug: 'sweet-potatoes',
    category: 'vegetables',
    subcategory: 'Root Vegetables',
    description: 'Delicious sweet potatoes rich in fiber and vitamins. Great for roasting, mashing, or baking.',
    shortDescription: 'Nutritious sweet potatoes',
    price: 2.99,
    discountedPrice: 2.49,
    currency: 'USD',
    stockQuantity: 180,
    unit: 'kg',
    weight: 1,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-10', url: 'https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=600&h=400&fit=crop', alt: 'Sweet Potatoes', isPrimary: true },
    ],
    tags: ['root', 'nutritious', 'versatile'],
    sku: 'VEG-SWEET-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 2,
    averageRating: 4.7,
    totalReviews: 42,
    isFeatured: true,
    isOnSale: true,
    createdAt: '2024-01-09T10:00:00Z',
    updatedAt: '2024-01-09T10:00:00Z',
  },
  // Grains
  {
    id: 'prod-10',
    sellerId: 'seller-3',
    sellerName: 'Ncube Grain Traders',
    sellerRating: 4.5,
    sellerBadges: ['verified', 'premium'],
    name: 'White Maize Meal',
    slug: 'white-maize-meal',
    category: 'grains',
    subcategory: 'Maize',
    description: 'Premium quality white maize meal. The staple food for traditional sadza.',
    shortDescription: 'Premium white maize meal for sadza',
    price: 4.99,
    currency: 'USD',
    stockQuantity: 500,
    unit: 'bag',
    weight: 5,
    weightUnit: 'kg',
    freshnessType: 'dried',
    location: 'Mutare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery', 'nationwide'],
    images: [
      { id: 'img-11', url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=400&fit=crop', alt: 'White Maize Meal', isPrimary: true },
    ],
    tags: ['staple', 'sadza', 'traditional'],
    sku: 'GRAIN-MAIZE-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.8,
    totalReviews: 89,
    isFeatured: true,
    isOnSale: false,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'prod-11',
    sellerId: 'seller-3',
    sellerName: 'Ncube Grain Traders',
    sellerRating: 4.5,
    sellerBadges: ['verified', 'premium'],
    name: 'Brown Rice',
    slug: 'brown-rice',
    category: 'grains',
    subcategory: 'Rice',
    description: 'Wholesome brown rice with natural fiber. A healthy alternative to white rice.',
    shortDescription: 'Wholesome brown rice',
    price: 6.99,
    currency: 'USD',
    stockQuantity: 250,
    unit: 'bag',
    weight: 2,
    weightUnit: 'kg',
    freshnessType: 'dried',
    location: 'Mutare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery', 'nationwide'],
    images: [
      { id: 'img-12', url: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=600&h=400&fit=crop', alt: 'Brown Rice', isPrimary: true },
    ],
    tags: ['healthy', 'fiber', 'wholesome'],
    sku: 'GRAIN-RICE-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.5,
    totalReviews: 67,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-11T10:00:00Z',
    updatedAt: '2024-01-11T10:00:00Z',
  },
  // Fruits
  {
    id: 'prod-12',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Fresh Mangoes',
    slug: 'fresh-mangoes',
    category: 'fruits',
    subcategory: 'Tropical',
    description: 'Sweet and juicy fresh mangoes. Perfect for eating fresh or making smoothies.',
    shortDescription: 'Sweet juicy fresh mangoes',
    price: 4.99,
    discountedPrice: 3.99,
    currency: 'USD',
    stockQuantity: 120,
    unit: 'kg',
    weight: 1,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-13', url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&h=400&fit=crop', alt: 'Fresh Mangoes', isPrimary: true },
    ],
    tags: ['tropical', 'sweet', 'smoothies'],
    sku: 'FRUIT-MANGO-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.8,
    totalReviews: 94,
    isFeatured: true,
    isOnSale: true,
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-12T10:00:00Z',
  },
  {
    id: 'prod-13',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Fresh Bananas',
    slug: 'fresh-bananas',
    category: 'fruits',
    subcategory: 'Tropical',
    description: 'Ripe yellow bananas. Great source of potassium and energy.',
    shortDescription: 'Ripe yellow bananas',
    price: 2.49,
    currency: 'USD',
    stockQuantity: 200,
    unit: 'bunch',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-14', url: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&h=400&fit=crop', alt: 'Fresh Bananas', isPrimary: true },
    ],
    tags: ['energy', 'potassium', 'snack'],
    sku: 'FRUIT-BANANA-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.4,
    totalReviews: 38,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-13T10:00:00Z',
    updatedAt: '2024-01-13T10:00:00Z',
  },
  {
    id: 'prod-14',
    sellerId: 'seller-3',
    sellerName: 'Ncube Grain Traders',
    sellerRating: 4.5,
    sellerBadges: ['verified', 'premium'],
    name: 'Dried Beans Mix',
    slug: 'dried-beans-mix',
    category: 'grains',
    subcategory: 'Legumes',
    description: 'Assorted dried beans including sugar beans, kidney beans, and black-eyed peas. Rich in protein.',
    shortDescription: 'Protein-rich dried beans mix',
    price: 5.49,
    currency: 'USD',
    stockQuantity: 300,
    unit: 'bag',
    weight: 2,
    weightUnit: 'kg',
    freshnessType: 'dried',
    location: 'Mutare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery', 'nationwide'],
    images: [
      { id: 'img-15', url: 'https://images.unsplash.com/photo-1515543904323-87f58cf67cdd?w=600&h=400&fit=crop', alt: 'Dried Beans', isPrimary: true },
    ],
    tags: ['protein', 'legumes', 'nutritious'],
    sku: 'GRAIN-BEANS-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.6,
    totalReviews: 52,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-14T10:00:00Z',
  },
  {
    id: 'prod-15',
    sellerId: 'seller-1',
    sellerName: 'Chikwanha Farms',
    sellerRating: 4.8,
    sellerBadges: ['verified', 'top_seller', 'trusted_farm'],
    name: 'Pork Sausages - Traditional',
    slug: 'pork-sausages-traditional',
    category: 'pork_meat',
    subcategory: 'Sausages',
    description: 'Traditional pork sausages made with our secret family recipe. Perfect for braai.',
    shortDescription: 'Traditional pork sausages for braai',
    price: 9.99,
    currency: 'USD',
    stockQuantity: 60,
    unit: 'pack',
    weight: 0.5,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Harare, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-16', url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop', alt: 'Pork Sausages', isPrimary: true },
    ],
    tags: ['sausages', 'braai', 'traditional'],
    sku: 'PORK-SAUSAGE-001',
    availabilityStatus: 'low_stock',
    minOrderQuantity: 1,
    averageRating: 4.9,
    totalReviews: 76,
    isFeatured: true,
    isOnSale: false,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'prod-16',
    sellerId: 'seller-2',
    sellerName: 'Moyo Fresh Vegetables',
    sellerRating: 4.6,
    sellerBadges: ['verified', 'fast_delivery'],
    name: 'Fresh Green Peppers',
    slug: 'fresh-green-peppers',
    category: 'vegetables',
    subcategory: 'Peppers',
    description: 'Crisp fresh green peppers. Perfect for salads, stir-fries, and stuffing.',
    shortDescription: 'Crisp fresh green peppers',
    price: 2.99,
    currency: 'USD',
    stockQuantity: 100,
    unit: 'kg',
    weight: 1,
    weightUnit: 'kg',
    freshnessType: 'fresh',
    location: 'Bulawayo, Zimbabwe',
    deliveryOptions: ['pickup', 'local_delivery'],
    images: [
      { id: 'img-17', url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&h=400&fit=crop', alt: 'Green Peppers', isPrimary: true },
    ],
    tags: ['fresh', 'salad', 'cooking'],
    sku: 'VEG-PEPPER-001',
    availabilityStatus: 'in_stock',
    minOrderQuantity: 1,
    averageRating: 4.5,
    totalReviews: 29,
    isFeatured: false,
    isOnSale: false,
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
];

// Mock Buyer
export const mockBuyer: BuyerProfile = {
  id: 'buyer-1',
  email: 'buyer@example.com',
  phone: '+263 77 555 1234',
  firstName: 'John',
  lastName: 'Mutasa',
  role: 'buyer',
  avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
  isVerified: true,
  savedAddresses: [],
  wishlist: ['prod-1', 'prod-5', 'prod-12'],
  recentlyViewed: ['prod-1', 'prod-2', 'prod-6', 'prod-10'],
  createdAt: '2023-06-15T10:00:00Z',
  updatedAt: '2024-01-15T10:00:00Z',
};

// Mock Addresses
export const mockAddresses: Address[] = [
  {
    id: 'addr-1',
    userId: 'buyer-1',
    label: 'Home',
    fullName: 'John Mutasa',
    phone: '+263 77 555 1234',
    street: '123 Samora Machel Avenue',
    city: 'Harare',
    province: 'Harare',
    country: 'Zimbabwe',
    postalCode: '00100',
    isDefault: true,
  },
  {
    id: 'addr-2',
    userId: 'buyer-1',
    label: 'Office',
    fullName: 'John Mutasa',
    phone: '+263 77 555 1234',
    street: '45 Nelson Mandela Avenue',
    city: 'Harare',
    province: 'Harare',
    country: 'Zimbabwe',
    postalCode: '00200',
    isDefault: false,
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'AGM-2024-001234',
    buyerId: 'buyer-1',
    sellerId: 'seller-1',
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        productName: 'Premium Pork Loin',
        productImage: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=600&h=400&fit=crop',
        quantity: 2,
        unitPrice: 10.99,
        totalPrice: 21.98,
        unit: 'kg',
      },
      {
        id: 'item-2',
        productId: 'prod-5',
        productName: 'Smoked Bacon Rashers',
        productImage: 'https://images.unsplash.com/photo-1606851181064-3939e5e5b3e1?w=600&h=400&fit=crop',
        quantity: 1,
        unitPrice: 14.99,
        totalPrice: 14.99,
        unit: 'pack',
      },
    ],
    status: 'delivered',
    paymentMethod: 'ecocash',
    paymentStatus: 'completed',
    deliveryAddress: mockAddresses[0],
    deliveryOption: 'local_delivery',
    subtotal: 36.97,
    deliveryFee: 3.00,
    discount: 0,
    total: 39.97,
    currency: 'USD',
    trackingNumber: 'TRK123456789',
    estimatedDelivery: '2024-01-10',
    createdAt: '2024-01-08T14:30:00Z',
    updatedAt: '2024-01-10T16:45:00Z',
  },
  {
    id: 'order-2',
    orderNumber: 'AGM-2024-001235',
    buyerId: 'buyer-1',
    sellerId: 'seller-2',
    items: [
      {
        id: 'item-3',
        productId: 'prod-6',
        productName: 'Organic Tomatoes',
        productImage: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=600&h=400&fit=crop',
        quantity: 3,
        unitPrice: 3.49,
        totalPrice: 10.47,
        unit: 'kg',
      },
    ],
    status: 'out_for_delivery',
    paymentMethod: 'visa',
    paymentStatus: 'completed',
    deliveryAddress: mockAddresses[0],
    deliveryOption: 'local_delivery',
    subtotal: 10.47,
    deliveryFee: 2.50,
    discount: 0,
    total: 12.97,
    currency: 'USD',
    trackingNumber: 'TRK123456790',
    estimatedDelivery: '2024-01-16',
    createdAt: '2024-01-14T09:15:00Z',
    updatedAt: '2024-01-15T11:30:00Z',
  },
  {
    id: 'order-3',
    orderNumber: 'AGM-2024-001236',
    buyerId: 'buyer-1',
    sellerId: 'seller-3',
    items: [
      {
        id: 'item-4',
        productId: 'prod-10',
        productName: 'White Maize Meal',
        productImage: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&h=400&fit=crop',
        quantity: 2,
        unitPrice: 4.99,
        totalPrice: 9.98,
        unit: 'bag',
      },
    ],
    status: 'processing',
    paymentMethod: 'onemoney',
    paymentStatus: 'completed',
    deliveryAddress: mockAddresses[1],
    deliveryOption: 'pickup',
    subtotal: 9.98,
    deliveryFee: 0,
    discount: 0,
    total: 9.98,
    currency: 'USD',
    createdAt: '2024-01-15T16:00:00Z',
    updatedAt: '2024-01-15T16:30:00Z',
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: 'review-1',
    productId: 'prod-1',
    buyerId: 'buyer-1',
    buyerName: 'John M.',
    buyerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    rating: 5,
    title: 'Excellent quality pork!',
    comment: 'The pork loin was incredibly tender and fresh. You can really taste the difference with free-range pork. Will definitely order again!',
    isVerifiedPurchase: true,
    helpfulCount: 12,
    createdAt: '2024-01-12T10:00:00Z',
    sellerResponse: {
      comment: 'Thank you for your kind words, John! We take pride in our quality. Looking forward to serving you again!',
      createdAt: '2024-01-12T14:30:00Z',
    },
  },
  {
    id: 'review-2',
    productId: 'prod-1',
    buyerId: 'buyer-2',
    buyerName: 'Sarah K.',
    rating: 4,
    title: 'Good quality, fast delivery',
    comment: 'Great pork, arrived fresh and well-packaged. Only giving 4 stars because the portion was slightly smaller than expected.',
    isVerifiedPurchase: true,
    helpfulCount: 5,
    createdAt: '2024-01-10T15:30:00Z',
  },
  {
    id: 'review-3',
    productId: 'prod-6',
    buyerId: 'buyer-3',
    buyerName: 'Peter N.',
    rating: 5,
    title: 'Best tomatoes in town!',
    comment: 'These organic tomatoes are amazing. So flavorful and fresh. Perfect for my salads.',
    isVerifiedPurchase: true,
    helpfulCount: 8,
    createdAt: '2024-01-11T12:00:00Z',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'buyer-1',
    type: 'order_update',
    title: 'Order Out for Delivery',
    message: 'Your order AGM-2024-001235 is out for delivery. Expected arrival today.',
    link: '/buyer/orders/order-2',
    isRead: false,
    createdAt: '2024-01-15T11:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'buyer-1',
    type: 'promotion',
    title: 'Weekend Sale!',
    message: 'Get 20% off on all pork products this weekend. Use code WEEKEND20.',
    link: '/products?category=pork_meat',
    isRead: false,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'buyer-1',
    type: 'payment',
    title: 'Payment Successful',
    message: 'Your payment of $12.97 for order AGM-2024-001235 was successful.',
    isRead: true,
    createdAt: '2024-01-14T09:20:00Z',
  },
  {
    id: 'notif-4',
    userId: 'seller-1',
    type: 'order_update',
    title: 'New Order Received',
    message: 'You have received a new order AGM-2024-001237. Please process it soon.',
    link: '/seller/orders/order-4',
    isRead: false,
    createdAt: '2024-01-15T14:00:00Z',
  },
  {
    id: 'notif-5',
    userId: 'seller-1',
    type: 'review',
    title: 'New Review',
    message: 'John M. left a 5-star review on Premium Pork Loin.',
    link: '/seller/reviews',
    isRead: true,
    createdAt: '2024-01-12T10:05:00Z',
  },
];

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: [
      { id: 'buyer-1', name: 'John Mutasa', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop', role: 'buyer' },
      { id: 'seller-1', name: 'Chikwanha Farms', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop', role: 'seller' },
    ],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-1',
      senderId: 'seller-1',
      senderName: 'Chikwanha Farms',
      content: 'Yes, we can arrange a bulk order for you. How many kilograms do you need?',
      isRead: false,
      createdAt: '2024-01-15T10:30:00Z',
    },
    unreadCount: 1,
    productId: 'prod-1',
    productName: 'Premium Pork Loin',
    createdAt: '2024-01-14T09:00:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
  },
];

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'buyer-1',
    senderName: 'John Mutasa',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    content: 'Hello, I am interested in ordering larger quantities of pork loin for my restaurant. Do you offer bulk pricing?',
    isRead: true,
    createdAt: '2024-01-14T09:00:00Z',
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'seller-1',
    senderName: 'Chikwanha Farms',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    content: 'Hello John! Thank you for your interest. Yes, we do offer bulk pricing for orders above 10kg. What quantity are you looking at?',
    isRead: true,
    createdAt: '2024-01-14T11:30:00Z',
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'buyer-1',
    senderName: 'John Mutasa',
    content: 'Great! I would need about 25kg per week for my restaurant.',
    isRead: true,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    senderId: 'seller-1',
    senderName: 'Chikwanha Farms',
    content: 'Yes, we can arrange a bulk order for you. How many kilograms do you need?',
    isRead: false,
    createdAt: '2024-01-15T10:30:00Z',
  },
];

// Mock Cart
export const mockCart: Cart = {
  id: 'cart-1',
  userId: 'buyer-1',
  items: [
    {
      id: 'cart-item-1',
      productId: 'prod-2',
      product: mockProducts.find(p => p.id === 'prod-2')!,
      quantity: 2,
      selectedDeliveryOption: 'local_delivery',
    },
    {
      id: 'cart-item-2',
      productId: 'prod-12',
      product: mockProducts.find(p => p.id === 'prod-12')!,
      quantity: 3,
      selectedDeliveryOption: 'local_delivery',
    },
  ],
  subtotal: 43.95,
  deliveryFee: 3.50,
  total: 47.45,
};

// Mock Seller Analytics
export const mockSellerAnalytics: SellerAnalytics = {
  totalRevenue: 15420.50,
  totalOrders: 324,
  totalProducts: 15,
  activeListings: 12,
  pendingOrders: 8,
  completedOrders: 298,
  averageRating: 4.8,
  revenueByMonth: [
    { month: 'Aug', revenue: 1200 },
    { month: 'Sep', revenue: 1450 },
    { month: 'Oct', revenue: 1680 },
    { month: 'Nov', revenue: 1890 },
    { month: 'Dec', revenue: 2340 },
    { month: 'Jan', revenue: 2150 },
  ],
  ordersByStatus: [
    { status: 'pending', count: 8 },
    { status: 'processing', count: 12 },
    { status: 'shipped', count: 6 },
    { status: 'delivered', count: 298 },
  ],
  topProducts: [
    { productId: 'prod-1', productName: 'Premium Pork Loin', sales: 87 },
    { productId: 'prod-5', productName: 'Smoked Bacon Rashers', sales: 120 },
    { productId: 'prod-15', productName: 'Pork Sausages', sales: 76 },
  ],
  recentOrders: mockOrders.slice(0, 3),
};

// Product Categories Data
export const productCategories = [
  {
    id: 'pork_meat',
    name: 'Pork Meat',
    description: 'Fresh and processed pork products',
    image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=400&h=300&fit=crop',
    subcategories: ['Loin', 'Ribs', 'Belly', 'Mince', 'Bacon', 'Sausages', 'Chops', 'Ham'],
  },
  {
    id: 'fresh_crops',
    name: 'Fresh Crops',
    description: 'Freshly harvested farm crops',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop',
    subcategories: ['Maize', 'Wheat', 'Sorghum', 'Millet'],
  },
  {
    id: 'vegetables',
    name: 'Vegetables',
    description: 'Fresh organic vegetables',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop',
    subcategories: ['Tomatoes', 'Leafy Greens', 'Onions', 'Peppers', 'Root Vegetables', 'Cabbage'],
  },
  {
    id: 'grains',
    name: 'Grains & Cereals',
    description: 'Quality grains and cereals',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop',
    subcategories: ['Maize', 'Rice', 'Wheat', 'Legumes', 'Oats'],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    description: 'Fresh seasonal fruits',
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    subcategories: ['Tropical', 'Citrus', 'Berries', 'Stone Fruits'],
  },
  {
    id: 'other_produce',
    name: 'Other Produce',
    description: 'Other farm products',
    image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=400&h=300&fit=crop',
    subcategories: ['Honey', 'Eggs', 'Dairy', 'Herbs'],
  },
];

// Testimonials
export const testimonials = [
  {
    id: 1,
    name: 'Tatenda Chirume',
    role: 'Restaurant Owner',
    location: 'Harare',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    rating: 5,
    comment: 'Agro Market has transformed how I source meat for my restaurant. The quality is consistent and delivery is always on time.',
  },
  {
    id: 2,
    name: 'Rumbidzai Moyo',
    role: 'Home Cook',
    location: 'Bulawayo',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    rating: 5,
    comment: 'Fresh vegetables delivered straight from the farm. The prices are fair and the quality is amazing!',
  },
  {
    id: 3,
    name: 'Takudzwa Phiri',
    role: 'Small Farmer',
    location: 'Mutare',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    rating: 5,
    comment: 'As a seller, Agro Market has helped me reach more customers than ever. The platform is easy to use and payments are reliable.',
  },
];

// FAQ Data
export const faqData = [
  {
    question: 'How does Agro Market work?',
    answer: 'Agro Market connects farmers and sellers directly with buyers. Sellers list their products, buyers browse and purchase, and we facilitate secure payments and delivery coordination.',
  },
  {
    question: 'What payment methods are accepted?',
    answer: 'We accept EcoCash, OneMoney, Visa cards, and PayPal. All payments are processed securely through our platform.',
  },
  {
    question: 'How is delivery handled?',
    answer: 'Sellers offer pickup or local delivery options. Delivery fees and times vary by seller and location. Some products are available for nationwide delivery.',
  },
  {
    question: 'How do I become a seller?',
    answer: 'Sign up as a seller, complete your business profile, upload verification documents, and start listing your products. Our team will review and approve your account within 24-48 hours.',
  },
  {
    question: 'Is my payment secure?',
    answer: 'Yes, all payments are processed through secure, encrypted channels. We hold funds in escrow until you confirm receipt of your order.',
  },
  {
    question: 'What if I receive a damaged product?',
    answer: 'Contact our support team within 24 hours of delivery with photos of the damage. We will arrange a refund or replacement depending on the situation.',
  },
];
